# Generated by Django 3.0.8 on 2020-07-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=255)),
                ('dept_phone', models.CharField(max_length=11)),
                ('people', models.DecimalField(decimal_places=4, max_digits=4)),
                ('teachers', models.DecimalField(decimal_places=4, max_digits=4)),
                ('a_chaw_sone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=255)),
                ('dept_phone', models.CharField(max_length=11)),
                ('people', models.DecimalField(decimal_places=4, max_digits=4)),
                ('teachers', models.DecimalField(decimal_places=4, max_digits=4)),
                ('a_chaw_sone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=255)),
                ('dept_phone', models.CharField(max_length=11)),
                ('people', models.DecimalField(decimal_places=4, max_digits=4)),
                ('teachers', models.DecimalField(decimal_places=4, max_digits=4)),
                ('a_chaw_sone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=255)),
                ('dept_phone', models.CharField(max_length=11)),
                ('people', models.DecimalField(decimal_places=4, max_digits=4)),
                ('teachers', models.DecimalField(decimal_places=4, max_digits=4)),
                ('a_chaw_sone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='mech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=255)),
                ('dept_phone', models.CharField(max_length=11)),
                ('people', models.DecimalField(decimal_places=4, max_digits=4)),
                ('teachers', models.DecimalField(decimal_places=4, max_digits=4)),
                ('a_chaw_sone', models.CharField(max_length=255)),
            ],
        ),
    ]
