# Generated by Django 3.0.8 on 2020-07-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='che',
            name='people',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='che',
            name='teachers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ec',
            name='people',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ec',
            name='teachers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='it',
            name='people',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='it',
            name='teachers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mc',
            name='people',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mc',
            name='teachers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mech',
            name='people',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mech',
            name='teachers',
            field=models.CharField(max_length=255),
        ),
    ]
